spring:
  profiles:
    default: "prod"

server:
  port: 5000

datasource:
  db:
    username: "sapphire"
    host: ${DATABASE_HOST}
    password: ${DATABASE_PASSWORD}

logging:
  level:
    root: "INFO"
  file: "/var/log/sapphire.log"

ebean:
  search:
    packages: "com.gleam.model"